### ISSUE TITLE
Feature: GUI - Version upgrade changes

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis#905]
### Current behavior

Hey,
We need to update the following sections in regard to the system update.

### Suggested solution

- [ ] Change the name of the page to "System information"

<img width="284" alt="Screen Shot 2023-04-25 at 10 49 45" src="https://user-images.githubusercontent.com/70286779/234210441-8f3bb65a-bb3d-4f85-9de1-bcc7b46a53ff.png">

- [ ] And in case there is a new version - add a badge "Update available" 

- [ ] Change the page itself with the following comments
<img width="1347" alt="Screen Shot 2023-04-25 at 10 41 17" src="https://user-images.githubusercontent.com/70286779/234212096-412b662d-453e-4169-a179-4d5bd182bfbf.png">
Link for docker - https://docs.memphis.dev/memphis/deployment/docker-compose#how-to-upgrade
Link for Kubernetes - https://docs.memphis.dev/memphis/deployment/kubernetes/how-to-upgrade

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by avrhamNeeman** [comment]
The relevant mock with the changes
<img width="1509" alt="Screenshot 2023-04-25 at 13 23 56" src="https://user-images.githubusercontent.com/74565114/234249312-a12ba090-7528-44bf-ab9a-ff02d7ffb14b.png">
